apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quiz
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ravisrma/quiz-app.git
    path: kubernetes-manifest
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: quiz
  syncPolicy:
    automated: {}