module.exports = {
  data: [
    {
      question: "What is the capital of India?",
      option1: "Mumbai",
      option2: "New Delhi",
      option3: "Kolkata",
      option4: "Chennai",
      ans: 2,
    },
    {
      question: "Who was the first Prime Minister of India?",
      option1: "Mahatma Gandhi",
      option2: "Jawaharlal Nehru",
      option3: "Sardar Patel",
      option4: "Dr. Rajendra Prasad",
      ans: 2,
    },
    {
      question: "What is the national animal of India?",
      option1: "Lion",
      option2: "Elephant",
      option3: "The Bengal Tiger",
      option4: "Peacock",
      ans: 3,
    },
    {
      question: "What is the national bird of India?",
      option1: "Sparrow",
      option2: "Crow",
      option3: "The Indian Peacock",
      option4: "Parrot",
      ans: 3,
    },
    {
      question: "Which river is considered the holiest in India?",
      option1: "Yamuna",
      option2: "Godavari",
      option3: "The Ganges River",
      option4: "Brahmaputra",
      ans: 3,
    },
    {
      question: "Which city is known as the 'Pink City' of India?",
      option1: "Jaipur",
      option2: "Jodhpur",
      option3: "Udaipur",
      option4: "Bikaner",
      ans: 1,
    },
    {
      question: "Who is known as the 'Father of the Nation' in India?",
      option1: "Subhash Chandra Bose",
      option2: "Mahatma Gandhi",
      option3: "Jawaharlal Nehru",
      option4: "Bhagat Singh",
      ans: 2,
    },
    {
      question: "What is the national fruit of India?",
      option1: "Apple",
      option2: "Banana",
      option3: "Mango",
      option4: "Guava",
      ans: 3,
    },
    {
      question: "How many colors are there in the Indian flag?",
      option1: "Two",
      option2: "Three",
      option3: "Four",
      option4: "Five",
      ans: 2,
    },
    {
      question: "Who wrote the Indian national anthem?",
      option1: "Rabindranath Tagore",
      option2: "Bankim Chandra Chatterjee",
      option3: "Sarojini Naidu",
      option4: "Subhash Chandra Bose",
      ans: 1,
    },
    {
      question: "Which is the largest state in India by area?",
      option1: "Madhya Pradesh",
      option2: "Maharashtra",
      option3: "Rajasthan",
      option4: "Uttar Pradesh",
      ans: 3,
    },
    {
      question: "What is the national currency of India?",
      option1: "Dollar",
      option2: "Euro",
      option3: "Indian Rupee",
      option4: "Pound",
      ans: 3,
    },
    {
      question: "Which sport is considered the most popular in India?",
      option1: "Hockey",
      option2: "Football",
      option3: "Cricket",
      option4: "Badminton",
      ans: 3,
    },
    {
      question: "What is the national flower of India?",
      option1: "Rose",
      option2: "Lotus",
      option3: "Marigold",
      option4: "Sunflower",
      ans: 2,
    },
    {
      question: "How many states does India have?",
      option1: "28",
      option2: "29",
      option3: "30",
      option4: "31",
      ans: 1,
    },
    {
      question: "What is the official language of India?",
      option1: "Hindi",
      option2: "English",
      option3: "Tamil",
      option4: "Bengali",
      ans: 1,
    },
    {
      question: "In which year did India gain independence from British rule?",
      option1: "1945",
      option2: "1946",
      option3: "1947",
      option4: "1948",
      ans: 3,
    },
    {
      question: "What is the national tree of India?",
      option1: "Neem",
      option2: "Banyan tree",
      option3: "Peepal tree",
      option4: "Mango tree",
      ans: 2,
    },
    {
      question: "Which Indian city is known as the 'Silicon Valley of India'?",
      option1: "Hyderabad",
      option2: "Bengaluru",
      option3: "Chennai",
      option4: "Pune",
      ans: 2,
    },
    {
      question: "Who was the first Indian woman to go to space?",
      option1: "Kalpana Chawla",
      option2: "Sunita Williams",
      option3: "Rakesh Sharma",
      option4: "Indira Gandhi",
      ans: 1,
    },
    {
      question: "What is the highest mountain in India?",
      option1: "Mount Everest",
      option2: "Kangchenjunga",
      option3: "Nanda Devi",
      option4: "K2",
      ans: 2,
    },
    {
      question: "What is the name of the famous festival of lights celebrated in India?",
      option1: "Holi",
      option2: "Diwali",
      option3: "Eid",
      option4: "Christmas",
      ans: 2,
    },
    {
      question: "Which Indian state is famous for its tea gardens?",
      option1: "Assam",
      option2: "Kerala",
      option3: "West Bengal",
      option4: "Tamil Nadu",
      ans: 1,
    },
    {
      question: "Who is known as the 'Missile Man of India'?",
      option1: "Dr. A.P.J. Abdul Kalam",
      option2: "Homi Bhabha",
      option3: "Vikram Sarabhai",
      option4: "C.V. Raman",
      ans: 1,
    },
    {
      question: "What is the name of the national aquatic animal of India?",
      option1: "Dolphin",
      option2: "Ganges River Dolphin",
      option3: "Whale",
      option4: "Shark",
      ans: 2,
    },
    {
      question: "Which Indian festival is known as the 'Festival of Colors'?",
      option1: "Diwali",
      option2: "Holi",
      option3: "Eid",
      option4: "Christmas",
      ans: 2,
    },
    {
      question: "Which country shares the longest border with India?",
      option1: "China",
      option2: "Pakistan",
      option3: "Bangladesh",
      option4: "Nepal",
      ans: 3,
    },
    {
      question: "What is the main ingredient of the dish 'Biryani'?",
      option1: "Rice",
      option2: "Wheat",
      option3: "Lentils",
      option4: "Vegetables",
      ans: 1,
    },
    {
      question: "Which is the longest river in India?",
      option1: "Yamuna",
      option2: "Godavari",
      option3: "The Ganges River",
      option4: "Brahmaputra",
      ans: 3,
    },
    {
      question: "What is the traditional dress for women in India?",
      option1: "Sari",
      option2: "Salwar Kameez",
      option3: "Lehenga",
      option4: "Kurta",
      ans: 1,
    },
    {
      question: "Who was the first President of India?",
      option1: "Dr. Rajendra Prasad",
      option2: "Jawaharlal Nehru",
      option3: "Sardar Patel",
      option4: "Mahatma Gandhi",
      ans: 1,
    },
    {
      question: "What is the Indian national song?",
      option1: "Jana Gana Mana",
      option2: "Vande Mataram",
      option3: "Saare Jahan Se Achha",
      option4: "Ae Mere Watan Ke Logon",
      ans: 2,
    },
    {
      question: "Which state in India is famous for its backwaters?",
      option1: "Kerala",
      option2: "Goa",
      option3: "Tamil Nadu",
      option4: "Karnataka",
      ans: 1,
    },
    {
      question: "Which Indian leader's birthday is celebrated as Children's Day?",
      option1: "Mahatma Gandhi",
      option2: "Jawaharlal Nehru",
      option3: "Sardar Patel",
      option4: "Dr. Rajendra Prasad",
      ans: 2,
    },
    {
      question: "What is the name of India's famous space research organization?",
      option1: "NASA",
      option2: "ISRO",
      option3: "DRDO",
      option4: "BARC",
      ans: 2,
    },
    {
      question: "What is the famous monument in Agra called?",
      option1: "Red Fort",
      option2: "Qutub Minar",
      option3: "The Taj Mahal",
      option4: "India Gate",
      ans: 3,
    },
    {
      question: "Which animal is used as a symbol of wisdom in Indian culture?",
      option1: "Elephant",
      option2: "Tiger",
      option3: "Peacock",
      option4: "Cow",
      ans: 1,
    },
    {
      question: "What is the traditional Indian drink made with yogurt called?",
      option1: "Lassi",
      option2: "Chai",
      option3: "Sharbat",
      option4: "Thandai",
      ans: 1,
    },
    {
      question: "Which Indian state is famous for its deserts?",
      option1: "Rajasthan",
      option2: "Gujarat",
      option3: "Punjab",
      option4: "Haryana",
      ans: 1,
    },
    {
      question: "What is the famous classical dance form from Tamil Nadu?",
      option1: "Kathak",
      option2: "Bharatanatyam",
      option3: "Odissi",
      option4: "Kuchipudi",
      ans: 2,
    },
    {
      question: "In which city is the Gateway of India located?",
      option1: "Delhi",
      option2: "Mumbai",
      option3: "Kolkata",
      option4: "Chennai",
      ans: 2,
    },
    {
      question: "Which Indian leader is known as the 'Iron Man of India'?",
      option1: "Mahatma Gandhi",
      option2: "Sardar Vallabhbhai Patel",
      option3: "Jawaharlal Nehru",
      option4: "Subhash Chandra Bose",
      ans: 2,
    },
    {
      question: "What is the currency symbol of the Indian Rupee?",
      option1: "$",
      option2: "₹",
      option3: "€",
      option4: "£",
      ans: 2,
    },
    {
      question: "Who was the first Indian woman to win an Olympic medal?",
      option1: "P.T. Usha",
      option2: "Karnam Malleswari",
      option3: "Mary Kom",
      option4: "Saina Nehwal",
      ans: 2,
    },
    {
      question: "What is the southernmost point of India called?",
      option1: "Kanyakumari",
      option2: "Indira Point",
      option3: "Rameswaram",
      option4: "Lakshadweep",
      ans: 2,
    },
    {
      question: "What is the official residence of the President of India called?",
      option1: "Rashtrapati Bhavan",
      option2: "Parliament House",
      option3: "Prime Minister's Residence",
      option4: "India Gate",
      ans: 1,
    },
    {
      question: "Which Indian classical music instrument is often associated with Pandit Ravi Shankar?",
      option1: "Sitar",
      option2: "Tabla",
      option3: "Veena",
      option4: "Flute",
      ans: 1,
    },
    {
      question: "What is the largest desert in India?",
      option1: "The Thar Desert",
      option2: "The Rann of Kutch",
      option3: "The Deccan Plateau",
      option4: "The Ladakh Desert",
      ans: 1,
    },
    {
      question: "Which city is known as the 'City of Joy' in India?",
      option1: "Mumbai",
      option2: "Kolkata",
      option3: "Delhi",
      option4: "Chennai",
      ans: 2,
    },
    {
      question: "What is the highest civilian award in India?",
      option1: "Padma Shri",
      option2: "Padma Bhushan",
      option3: "Bharat Ratna",
      option4: "Padma Vibhushan",
      ans: 3,
    },
  ],
};